### ISSUE TITLE
Unexpected token . in JSON at position 0

### ISSUE THREAD

**Issue by flameshikari** [kevin-david/promote-play-release#113]
Hello!

The action fails with `Unexpected token . in JSON at position 0`
JSON is 100% valid (checked with jq)
Is there anything else I can provide to fix the problem?

### The workflow step
```yml
...

- uses: kevin-david/promote-play-release@v1.0.0
  with:
    service-account-json-raw: service_account.json
    package-name: [REDACTED]
    inapp-update-priority: 5
    user-fraction: 1.0

...
```

### service_account.json (edited)
```json
{
  "type": "service_account",
  "project_id": "[REDACTED]",
  "private_key_id": "[REDACTED]",
  "private_key": "[REDACTED]",
  "client_email": "[REDACTED]",
  "client_id": "",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "[REDACTED]"
}
```
