### ISSUE TITLE
Provide Input for `service-account-json` as a file.

### ISSUE THREAD

**Issue by Bwvolleyball** [kevin-david/promote-play-release#284]
I'm using the recommended google auth action to create ephemeral service account json tokens, and I want this action to support reading the service account json from a file in addition to the raw format.

For example, here's my auth step:

```
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: <identity>
          service_account: <svc-account>
```

Currently, in the `upload-google-play` action, I can then just reference the file created by this step to auth.

```
      - name: Deploy to Google Play Store - Internal
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ steps.auth.outputs.credentials_file_path }}
          packageName: <pkg>
          releaseFiles: <file>
          track: internal
          status: completed
```

This just reads the file. I'd like to do the same for this action to promote from internal to production
