### ISSUE TITLE
changesNotSentForReview set to true error

### ISSUE THREAD

**Issue by dfloresgonz** [kevin-david/promote-play-release#286]
I had to go to play console and promote it manually, any workarounds?

```
Creating a new app edit
Getting current internal info
Switching internal release to production
Committing changes
Error: Changes cannot be sent for review automatically. Please set the query parameter changesNotSentForReview to true. Once committed, the changes in this edit can be sent for review from the Google Play Console UI.
```

```yaml
    - name: Promote Release
      uses: kevin-david/promote-play-release@v1.1.0
      with:
        service-account-json-raw: ${{ secrets.PLAY_STORE_JSON_KEY }}
        package-name: ${{ env.PACKAGE_NAME }}
        user-fraction: 1.0
#          inapp-update-priority: 0
        from-track: internal
        to-track: production
```
